### ISSUE TITLE
Issues intalling with pip/conda

### ISSUE THREAD

**Issue by stevenstetzler** [B612-Asteroid-Institute/precovery#19]
I have run into issues installing the requirements using conda/pip. I initially tried installing with `pip` using `requirements.txt` and `dev-requirements.txt` per the README:
```
conda create -n precovery python=3.10
conda activate precovery
# python3.10 -m venv virtualenv3.10 # ignore since I installed python3.10 with conda
# source virtualenv3.10/bin/activate # ignore since I made a conda env
pip install pip --upgrade
pip install -r requirements.txt -r dev-requirements.txt
pre-commit install
```
gave errors saying that `llvmlite==0.36.0` and `numba==0.53.1` were not available, making the fixed versions impossible to install.

I think installed using the `requirements.in` and  `dev-requirements.in` files, where only `numpy` and `numba` are versioned and  continued to receive an error since `numba==0.53.1` is defined in `requirements.in`. I replaced `numba==0.53.1` with `numba==0.55.1` which led to a solve. Finally, pip installed `numpy` version `1.22` but `numba` threw errors on execution claiming in needs `numpy<=1.21`. I solved this with:
```
pip install numpy==1.21
```
And with that the `precovery` code ran.

Additionally, I needed to install `pyoorb`:
```
conda install openorb
```

I can make updates to the README and a pull request at a later time.

**Comment by moeyensj** [comment]
We relaxed the version requirements in PR #38, which has the side effect of fixing this issue. If problems persist please feel completely free to reopen here!
