### ISSUE TITLE
Make "E-mail me cutouts" off by default

### ISSUE THREAD

**Issue by mjuric** [B612-Asteroid-Institute/precovery#29]
Right now, "Email Me Candidate Cutouts" is checked by default. That keeps the 'submit' field greyed out until an e-mail is entered. An impatient/unobservant user (== yours truly) won't notice that and will get confused on why the 'Submit' field can't be clicked.

Proposed resolution: just make the "Email me candidate cutouts" checkbox off by default.

<img width="1020" alt="image" src="https://user-images.githubusercontent.com/620059/178755412-e08d71fc-895f-4d8b-a1aa-b2e7273376ca.png">

Related issue:

After typing in the e-mail, the 'Submit' button remains disabled until the focus moves away from it. This will be confusing to the user.

<img width="1159" alt="image" src="https://user-images.githubusercontent.com/620059/178757015-2133ea29-f3ec-4a58-95e9-51ed92f0f8af.png">

**Comment by ntellis** [comment]
This was updated in https://github.com/B612-Asteroid-Institute/b612-asteroid-institute.github.io/commit/53af2c9489ba2edb86f3bb7882b732d644017017
