### ISSUE TITLE
Disable the banner

### ISSUE THREAD

**Issue by mjuric** [B612-Asteroid-Institute/precovery#30]
Now that the "NYT wave" has passed & the page is effectively open, let's disable the warning banner.

<img width="1172" alt="image" src="https://user-images.githubusercontent.com/620059/178758343-24d7a6d5-345c-4cf0-9277-b7266244c558.png">

**Comment by ntellis** [comment]
This was updated in https://github.com/B612-Asteroid-Institute/b612-asteroid-institute.github.io/commit/53af2c9489ba2edb86f3bb7882b732d644017017
